[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    # JSON Parsing (Version 7)
    bblanchon/ArduinoJson @ ^7.0.4
    
    # MQTT Communication
    knolleary/PubSubClient @ ^2.8
    
    # I2C LCD Display
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
    
    # Matrix Keypad
    chris--a/Keypad @ ^3.1.1    
    # RFID MFRC522
    miguelbalboa/MFRC522 @ ^1.4.11