[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial Monitor speed (must match Serial.begin(115200) in your code)
monitor_speed = 115200

lib_deps =
    # MQTT Library by knolleary
    knolleary/PubSubClient @ ^2.8
    
    # JSON Library by Benoit Blanchon
    bblanchon/ArduinoJson @ ^7.0.4