[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    # Modern JSON Library
    bblanchon/ArduinoJson @ ^7.0.4
    
    # MQTT Communication
    knolleary/PubSubClient @ ^2.8
    
    # LCD Display
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2